### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by ch11en** [Johnny-Haytham/Vim#1]
Traceback (most recent call last):
  File "/ssd-data1/cxf2022/main_correct.py", line 449, in <module>
    test()
  File "/ssd-data1/cxf2022/main_correct.py", line 427, in test
    model = VisionMamba(
  File "/ssd-data1/cxf2022/main_correct.py", line 234, in __init__
    [
  File "/ssd-data1/cxf2022/main_correct.py", line 235, in <listcomp>
    create_block(
  File "/ssd-data1/cxf2022/main_correct.py", line 135, in create_block
    norm_cls=partial(nn.LayerNorm if not rms_norm else RMSNorm,eps=norm_epsilon,**factory_kwargs)  #eps用于避免归一化过程中分母为0的情况
TypeError: the first argument must be callable

Process finished with exit code 1

请问这怎么解决

**Comment by 121dyy** [comment]
> Traceback (most recent call last): File "/ssd-data1/cxf2022/main_correct.py", line 449, in test() File "/ssd-data1/cxf2022/main_correct.py", line 427, in test model = VisionMamba( File "/ssd-data1/cxf2022/main_correct.py", line 234, in **init** [ File "/ssd-data1/cxf2022/main_correct.py", line 235, in create_block( File "/ssd-data1/cxf2022/main_correct.py", line 135, in create_block norm_cls=partial(nn.LayerNorm if not rms_norm else RMSNorm,eps=norm_epsilon,**factory_kwargs) #eps用于避免归一化过程中分母为0的情况 TypeError: the first argument must be callable
> 
> Process finished with exit code 1
> 
> 请问这怎么解决

我也遇到了相同的问题，请问您找到解决办法了吗

**Comment by whjzsy** [comment]
请问问题解决了吗？我也遇到相同的问题
